// Code generated by "stringer -type=fieldType"; DO NOT EDIT.

package docgen

import "strconv"

const _fieldType_name = "ftUnknownftArrayftObjectftItemftMixinInstanceftConstructor"

var _fieldType_index = [...]uint8{0, 9, 16, 24, 30, 45, 58}

func (i fieldType) String() string {
	if i < 0 || i >= fieldType(len(_fieldType_index)-1) {
		return "fieldType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _fieldType_name[_fieldType_index[i]:_fieldType_index[i+1]]
}
