// Code generated by "stringer -type=propertyType"; DO NOT EDIT.

package docgen

import "strconv"

const _propertyType_name = "ptFunctionptMixinptTypeptConstructor"

var _propertyType_index = [...]uint8{0, 10, 17, 23, 36}

func (i propertyType) String() string {
	if i < 0 || i >= propertyType(len(_propertyType_index)-1) {
		return "propertyType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _propertyType_name[_propertyType_index[i]:_propertyType_index[i+1]]
}
